-- ex1: leetcode-mmediate-food-delivery.
-- ex2: leetcode-game-play-analysis.
-- ex3: leetcode-exchange-seats.
-- ex4: leetcode-restaurant-growth.
-- ex5: leetcode-investments-in-2016.
-- ex6: leetcode-department-top-three-salaries.
-- ex7: leetcode-last-person-to-fit-in-the-bus.
-- ex8: leetcode-product-price-at-a-given-date.
